---

  - name: 'Create ansible working directory'
    file: path={{ working_directory }} state=directory

  - name: 'Create .aws folder'
    file:
      path: "~/.aws"
      state: directory
      mode: 0755

  - name: 'Add aws credentials'
    blockinfile:
      dest: '~/.aws/credentials'
      create: yes
      content: |
        [default]
        aws_access_key_id={{ aws_access_key_id }}
        aws_secret_access_key={{ aws_secret_access_key }}

  - name: 'Set aws_ssm_path'
    set_fact:
      aws_ssm_path: "/{{ release_namespace.split('-') | join('/') }}"

  - name: 'Print namespace'
    debug:
      msg: '{{ release_namespace }}'

  - name: 'Print projet'
    debug:
      msg: '{{ release_project }}'

  - name: 'Print version'
    debug:
      msg: '{{ release_version }}'

  - name: 'Print aws_ssm_path'
    debug:
      msg: '{{ aws_ssm_path }}'
