---

  - name: 'Install helm charts'
    helm:
      chart:
        name: '{{ item.chart }}'
        version: '{{ item.version }}'
        source:
          type: '{{ item.type }}'
          location: '{{ item.location }}'
      state: installed
      name: '{{ item.name }}'
      namespace: '{{ release_namespace }}'
    with_items: '{{ helm_charts }}'
    register: 'helm_output'

  - name: 'Print helm output'
    debug:
      msg: '{{ helm_output }}'
